apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/salihDIALLO/wordpress-k8s-project.git
    targetRevision: main
    path: base/wordpress
  destination:
    server: https://kubernetes.default.svc
    namespace: default  # <- revenir Ã  default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
