name: Build and Push WordPress Image

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "src/**"
      - ".github/workflows/build-wordpress.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code du repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Connexion à GHCR avec token stocké dans GitHub Secrets
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # 3️⃣ Construire l'image Docker (noms en minuscules)
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/salihdiallo/wordpress-k8s-project/wordpress:latest .

      # 4️⃣ Pousser l'image sur GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/salihdiallo/wordpress-k8s-project/wordpress:latest
