
name: Build, Push and Deploy WordPress Image

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - ".github/workflows/build-wordpress.yaml"
      - "base/jx/**"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Login to GHCR using PAT
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: salihdiallo
          password: ${{ secrets.GHCR_PAT }}

      # 3️⃣ Build Docker image (all lowercase)
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/salihdiallo/wordpress-k8s-project/wordpress:latest .

      # 4️⃣ Push Docker image to GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/salihdiallo/wordpress-k8s-project/wordpress:latest

      # 5️⃣ Update values-staging.yaml with new image tag
      - name: Update values-staging.yaml
        run: |
          sed -i 's|image:.*|image: "ghcr.io/salihdiallo/wordpress-k8s-project/wordpress:latest"|' base/jx/values-staging.yaml

      # 6️⃣ Commit and push updated values.yaml for ArgoCD
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add base/jx/values-staging.yaml
          git commit -m "Update WordPress image to latest tag [skip ci]" || echo "No changes to commit"
          git push origin main
